### PR TITLE
confidenceAnnotation_Indels.py updated to latest version

### PR DESCRIPTION
**Pull request by kubranarci**
Update of the script is from here: https://github.com/DKFZ-ODCF/IndelCallingWorkflow/pull/19/commits/cdd19887182fbb59167c77b77f4dd922bed03917

### CODE REVIEW

**Comment by NagaComBio** [comment]
Great! `MAFCommon` is present in the normal VCF file. Please add it to the `convertToStdVCF.json` file, so standard VCF files also get them.

**Comment by kubranarci** [comment]
> MAFCommon

I couldnt find it, can you show me an example field? where to add it.

**Comment by NagaComBio** [comment]
Here is an example: 

The `MAFCommon` label is in the INFO column for the normal VCF. 
```
chr1    600162  rs1413752627_600162     GCCATTT G       .       PASS    SOMATIC;MAFCommon;BRF=0.34;FR=0.2500;HP=2;HapScore=1;MGOF=9;MMLQ=37;MQ=23.49;NF=3;NR=0;PP=387;QD=147.425945567;SC=CCAATTATCAGCCATTTCTCC;SbPval=1.0;Source=Platypus;TC=119;TCF=87;TCR=32;TR=3;WE=600180;WS=600152      GT:GL:GOF:GQ:NR:NV      0/0:0.0,-15.35,-299.4:6:99:57:0 0/1:-16.5,0.0,-299.7:9:99:62:3  MATCH=exact;POS=600162;END=600168;RS=1413752627;RSPOS=600163;dbSNPBuildID=151;SSR=0;SAO=0;VP=0x050000080005000002000200;GENEINFO=LOC105378947:105378947;WGT=1;VC=DIV;INT;ASP;TOPMED=0.97190366972477064,0.02809633027522935;ID=rs1413752627   .       .       .       MATCH=exact;AC=1108;AN=87524;AF=0.012659399770200253;fAF_95=0.012039399705827236;fAF_99=0.012039899826049805;AF_afr=0.03408379852771759;AF_amr=0.011486000381410122;AF_eas=0.027421200647950172;AF_fin=0.005234859883785248;AF_nfe=0.006672159768640995;AF_sas=0.010113799944519997;AF_oth=0.012738900259137154;HOMO=0;HOMO_nfe=0;HOMO_sas=0;FILTER=AS_VQSR .       intergenic      ENSG00000235146(dist=5395),ENSG00000278791(dist=32157)  .       .       Score=0.995171;Name=chr1:357216 1p36.33 LINE_L1_L1MC4a  0.166667        .       somatic 8       7       .    ..       .       .       .       ID=LINC00115:24;gene_id=LINC00115;transcript_id=LINC00115:24;gene_alias_1=FLJ22639;transcript_alias_1=ENSG00000240453.1|FTMT20100027364.1;sncType=lnc_RNA&ID=LINC00115:25;gene_id=LINC00115;transcript_id=LINC00115:25;gene_alias_1=FLJ22639;transcript_alias_1=ENSG00000240453.1|FTMT20100026364.1;sncType=lnc_RNA&ID=LINC00115:19;gene_id=LINC00115;transcript_id=LINC00115:19;gene_alias_1=ENSG00000230021.8;gene_alias_2=RP5-857K21.4;gene_alias_3=FLJ22639;transcript_alias_1=ENST00000634833.1;sncType=lnc_RNA&ID=LINC00115:3;gene_id=LINC00115;transcript_id=LINC00115:3;gene_alias_1=ENSG00000230021.8;gene_alias_2=RP5-857K21.4;gene_alias_3=FLJ22639;transcript_alias_1=ENST00000635509.1;sncType=lnc_RNA&ID=LINC00115:2;gene_id=LINC00115;transcript_id=LINC00115:2;gene_alias_1=ENSG00000230021.8;gene_alias_2=RP5-857K21.4;gene_alias_3=FLJ22639;transcript_alias_1=ENST00000634337.1;sncType=lnc_RNA
```

But not in the Std VCF for the same variant
```
chr1    600162  rs1413752627_600162     GCCATTT G       .       PASS    MIR=.;FR=0.25;MMLQ=37;DNS=.;ENH=.;TR=3;HP=2;WE=600180;MGOF=9;SbPval=1;Source=Platypus;TFBS=.;WS=600152;CONF=8;CPG=.;SEGDUP=Score=0.995171,Name=chr1:357216;PP=387;HapScore=1;SNC=ID=LINC00115:24,gene_id=LINC00115,transcript_id=LINC00115:24,gene_alias_1=FLJ22639,transcript_alias_1=ENSG00000240453.1|FTMT20100027364.1,sncType=lnc_RNA&ID=LINC00115:25,gene_id=LINC00115,transcript_id=LINC00115:25,gene_alias_1=FLJ22639,transcript_alias_1=ENSG00000240453.1|FTMT20100026364.1,sncType=lnc_RNA&ID=LINC00115:19,gene_id=LINC00115,transcript_id=LINC00115:19,gene_alias_1=ENSG00000230021.8,gene_alias_2=RP5-857K21.4,gene_alias_3=FLJ22639,transcript_alias_1=ENST00000634833.1,sncType=lnc_RNA&ID=LINC00115:3,gene_id=LINC00115,transcript_id=LINC00115:3,gene_alias_1=ENSG00000230021.8,gene_alias_2=RP5-857K21.4,gene_alias_3=FLJ22639,transcript_alias_1=ENST00000635509.1,sncType=lnc_RNA&ID=LINC00115:2,gene_id=LINC00115,transcript_id=LINC00115:2,gene_alias_1=ENSG00000230021.8,gene_alias_2=RP5-857K21.4,gene_alias_3=FLJ22639,transcript_alias_1=ENST00000634337.1,sncType=lnc_RNA;CYTOBAND=1p36.33;ANNOVARFUN=intergenic;COS=.;TCR=32;NF=3;REP=.;ANNOVARTR=.;EXONICCL=.;SC=CCAATTATCAGCCATTTCTCC;BRF=0.34;NR=0;TCF=87;TC=119;GENE=ENSG00000235146(dist=5395),ENSG00000278791(dist=32157)    GT:GL:GOF:GQ:NR:NV      0/0:0,-15.35,-299.4:6:99:57:0   0/1:-16.5,0,-299.7:9:99:62:3
```

Similar to the "INDEL" flag in `convertToStdVCF.json`, add `MAFCommon` to the `convertToStdVCF.json`, as the following: 
```
    "MAFCommon": {
      "number": "0",
      "type": "Flag",
      "description": "Indicates that the variant is common in the gnomAD or local controls."
    },
```
I don't know if we need to specify anywhere else that we need this flag in the final file.

**Comment by kubranarci** [comment]
> Here is an example:
> 
> The `MAFCommon` label is in the INFO column for the normal VCF.
> 
> ```
> chr1    600162  rs1413752627_600162     GCCATTT G       .       PASS    SOMATIC;MAFCommon;BRF=0.34;FR=0.2500;HP=2;HapScore=1;MGOF=9;MMLQ=37;MQ=23.49;NF=3;NR=0;PP=387;QD=147.425945567;SC=CCAATTATCAGCCATTTCTCC;SbPval=1.0;Source=Platypus;TC=119;TCF=87;TCR=32;TR=3;WE=600180;WS=600152      GT:GL:GOF:GQ:NR:NV      0/0:0.0,-15.35,-299.4:6:99:57:0 0/1:-16.5,0.0,-299.7:9:99:62:3  MATCH=exact;POS=600162;END=600168;RS=1413752627;RSPOS=600163;dbSNPBuildID=151;SSR=0;SAO=0;VP=0x050000080005000002000200;GENEINFO=LOC105378947:105378947;WGT=1;VC=DIV;INT;ASP;TOPMED=0.97190366972477064,0.02809633027522935;ID=rs1413752627   .       .       .       MATCH=exact;AC=1108;AN=87524;AF=0.012659399770200253;fAF_95=0.012039399705827236;fAF_99=0.012039899826049805;AF_afr=0.03408379852771759;AF_amr=0.011486000381410122;AF_eas=0.027421200647950172;AF_fin=0.005234859883785248;AF_nfe=0.006672159768640995;AF_sas=0.010113799944519997;AF_oth=0.012738900259137154;HOMO=0;HOMO_nfe=0;HOMO_sas=0;FILTER=AS_VQSR .       intergenic      ENSG00000235146(dist=5395),ENSG00000278791(dist=32157)  .       .       Score=0.995171;Name=chr1:357216 1p36.33 LINE_L1_L1MC4a  0.166667        .       somatic 8       7       .    ..       .       .       .       ID=LINC00115:24;gene_id=LINC00115;transcript_id=LINC00115:24;gene_alias_1=FLJ22639;transcript_alias_1=ENSG00000240453.1|FTMT20100027364.1;sncType=lnc_RNA&ID=LINC00115:25;gene_id=LINC00115;transcript_id=LINC00115:25;gene_alias_1=FLJ22639;transcript_alias_1=ENSG00000240453.1|FTMT20100026364.1;sncType=lnc_RNA&ID=LINC00115:19;gene_id=LINC00115;transcript_id=LINC00115:19;gene_alias_1=ENSG00000230021.8;gene_alias_2=RP5-857K21.4;gene_alias_3=FLJ22639;transcript_alias_1=ENST00000634833.1;sncType=lnc_RNA&ID=LINC00115:3;gene_id=LINC00115;transcript_id=LINC00115:3;gene_alias_1=ENSG00000230021.8;gene_alias_2=RP5-857K21.4;gene_alias_3=FLJ22639;transcript_alias_1=ENST00000635509.1;sncType=lnc_RNA&ID=LINC00115:2;gene_id=LINC00115;transcript_id=LINC00115:2;gene_alias_1=ENSG00000230021.8;gene_alias_2=RP5-857K21.4;gene_alias_3=FLJ22639;transcript_alias_1=ENST00000634337.1;sncType=lnc_RNA
> ```
> 
> But not in the Std VCF for the same variant
> 
> ```
> chr1    600162  rs1413752627_600162     GCCATTT G       .       PASS    MIR=.;FR=0.25;MMLQ=37;DNS=.;ENH=.;TR=3;HP=2;WE=600180;MGOF=9;SbPval=1;Source=Platypus;TFBS=.;WS=600152;CONF=8;CPG=.;SEGDUP=Score=0.995171,Name=chr1:357216;PP=387;HapScore=1;SNC=ID=LINC00115:24,gene_id=LINC00115,transcript_id=LINC00115:24,gene_alias_1=FLJ22639,transcript_alias_1=ENSG00000240453.1|FTMT20100027364.1,sncType=lnc_RNA&ID=LINC00115:25,gene_id=LINC00115,transcript_id=LINC00115:25,gene_alias_1=FLJ22639,transcript_alias_1=ENSG00000240453.1|FTMT20100026364.1,sncType=lnc_RNA&ID=LINC00115:19,gene_id=LINC00115,transcript_id=LINC00115:19,gene_alias_1=ENSG00000230021.8,gene_alias_2=RP5-857K21.4,gene_alias_3=FLJ22639,transcript_alias_1=ENST00000634833.1,sncType=lnc_RNA&ID=LINC00115:3,gene_id=LINC00115,transcript_id=LINC00115:3,gene_alias_1=ENSG00000230021.8,gene_alias_2=RP5-857K21.4,gene_alias_3=FLJ22639,transcript_alias_1=ENST00000635509.1,sncType=lnc_RNA&ID=LINC00115:2,gene_id=LINC00115,transcript_id=LINC00115:2,gene_alias_1=ENSG00000230021.8,gene_alias_2=RP5-857K21.4,gene_alias_3=FLJ22639,transcript_alias_1=ENST00000634337.1,sncType=lnc_RNA;CYTOBAND=1p36.33;ANNOVARFUN=intergenic;COS=.;TCR=32;NF=3;REP=.;ANNOVARTR=.;EXONICCL=.;SC=CCAATTATCAGCCATTTCTCC;BRF=0.34;NR=0;TCF=87;TC=119;GENE=ENSG00000235146(dist=5395),ENSG00000278791(dist=32157)    GT:GL:GOF:GQ:NR:NV      0/0:0,-15.35,-299.4:6:99:57:0   0/1:-16.5,0,-299.7:9:99:62:3
> ```
> 
> Similar to the "INDEL" flag in `convertToStdVCF.json`, add `MAFCommon` to the `convertToStdVCF.json`, as the following:
> 
> ```
>     "MAFCommon": {
>       "number": "0",
>       "type": "Flag",
>       "description": "Indicates that the variant is common in the gnomAD or local controls."
>     },
> ```
> 
> I don't know if we need to specify anywhere else that we need this flag in the final file.

okay, it is still being missed probably since it is a flag. Automatic extraction of those without = was problematic with the script. I have to restructure/rewrite it while adding info to .json.

**Comment by kubranarci** [comment]
Can you please review the new change? 

Is MAFcommon also included in snv calling? I will change the script accordingly if it does..

**Comment by NagaComBio** [comment]
- I have made the updates to ensure that the variant calls in `nf-platypusindelcalling` will match those in `Roddy-Indel-hg38`.
- Yes, for SNVs also we need to add the `MAFCommon` tag.

**Review by NagaComBio — APPROVED** [review]

**Pull request merged**
