### PR TITLE
39 add nf prov

### PR DESCRIPTION
**Pull request by kubranarci**
- nf-prov is added
- pipeline version updated to 2.0.0
- fix: with updates, make the version 2.0.1 as minor release

### CODE REVIEW

**Review by drewjbeh — APPROVED** [review]
Also looks good. Same comment as for https://github.com/ghga-de/nf-snvcalling/pull/41: can we also review a test BCO output?

**Comment by kubranarci** [comment]
[manifest_2024-10-09_15-51-34.bco.json](https://github.com/user-attachments/files/17325357/manifest_2024-10-09_15-51-34.bco.json)
 this is the output manifest.

**Comment by kubranarci** [comment]
I think it is the same as she looked :) comparing to sarek, "extension" is still missing. This is since these pipelines are not nf-core. nf-core pipelines emits github links directly I guess.

**Comment by mauerk** [comment]
Hey both, I checked the BCO and as @kubranarci said, the extension domain is still missing. I also checked the nf-prov BCO script to see how this domain is filled. 
It imports the [workflow metadata](https://github.com/nextflow-io/nf-prov/blob/master/plugins/nf-prov/src/main/nextflow/prov/BcoRenderer.groovy#L58) and uses it to fill fields in the provenance and execution domains, e.g. _name_, _version_, _creation date_. These fields are filled in the BCO for platypus. The extension domain is only filled when the repository information is present in the workflow metadata, which apparently is empty for platypus (see [here](https://github.com/nextflow-io/nf-prov/blob/master/plugins/nf-prov/src/main/nextflow/prov/BcoRenderer.groovy#L143)). The script that is used to get the workflow metadata should be [this](https://github.com/nextflow-io/nextflow/blob/master/modules/nextflow/src/main/groovy/nextflow/script/WorkflowMetadata.groovy).
Could you test nf-prov on another pipeline that is also not nf-core to see if that's the reason why the repository information is not filled?

**Comment by drewjbeh** [comment]
Thaks for looking into this Karo! Based on the results from [snvcalling ](https://github.com/ghga-de/nf-snvcalling/pull/41#issuecomment-2407057629) this seems to be the issue. @kubranarci if you have time could you look into what Karo linked here to see if we can get that metadata for extension domain loaded automatically?

**Pull request merged**
